packageExtensions:
  "@tarojs/mini-runner@*":
    dependencies:
      "autoprefixer": "*"
      "webpack-sources": "^2.3.1"
      "acorn-walk": "*"
  "postcss-pxtransform@*":
    dependencies:
      "object-assign": "*"
  "babel-preset-taro@*":
    dependencies:
      "lodash": "^4.7.0"
  "loader-runner@^2.4.0":
    dependencies:
      "@tarojs/taro-loader": "^3.4.12"
  "@tarojs/helper@*":
    dependencies:
      "@babel/parser": "*"
      "@babel/traverse": "*"
  "react-redux@*":
    dependencies:
      "@tarojs/react": "*"
  "taro-ui@*":
    dependencies:
      "@tarojs/taro": "*"
      "@tarojs/plugin-platform-weapp": "*"