# Build docker images

trigger:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_DISK_CACHE: $(Pipeline.Workspace)/.bazelcache
  BAZEL_OUTPUT_BASE: $(Pipeline.Workspace)/.bazel
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: 'ubuntu-latest'

steps:
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
- task: Cache@2
  displayName: "Cache: Bazel diskcache"
  inputs:
    key: 'bazel | "$(Agent.OS)" | disk | "$(Build.SourceVersion)"'
    restoreKeys: |
      bazel | "$(Agent.OS)" | disk
    path: $(BAZEL_DISK_CACHE)

- task: Cache@2
  displayName: "Cache: Bazel output base"
  inputs:
    key: 'bazel | "$(Agent.OS)" | outputbase | "$(Build.SourceVersion)"'
    restoreKeys: |
      bazel | "$(Agent.OS)" | outputbase
    path: $(BAZEL_OUTPUT_BASE)

- task: Cache@2
  displayName: "Cache: yarn"
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)

- task: Cache@2
  displayName: "Cache: node_modules"
  inputs:
    key: 'node_modules | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      node_modules | "$(Agent.OS)"
    path: node_modules

- script: |
    echo "startup --output_base=$(BAZEL_OUTPUT_BASE)
    common --color=no
    common --curses=yes

    build --disk_cache=$(BAZEL_DISK_CACHE)
    build --show_progress_rate_limit=0
    build --show_task_finish
    build --show_timestamps
    build --worker_verbose" >> .bazelrc

    cat .bazelrc

- script: |
    sudo apt install curl
    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    sudo apt update && sudo apt install -y bazel ffmpeg
    bazel version
  displayName: 'Install bazel, ffmpeg'

- script: |
    bazel build //web/src/...
  displayName: 'Bazel build //web/src/...'

- script: |
    bazel build //server/opencc_daemon:image //assets:tts_audio_wav_image &&
    bazel run //server/opencc_daemon:image &&
    bazel run //assets:tts_audio_wav_image &&
    docker tag bazel/server/opencc_daemon:image ztl8702/opencc-daemon:ci-$(Build.BuildNumber)
  displayName: 'Bazel build: OpenCC Daemon image, TTS Audio image'

- script: |
    ./docker_build.sh ci-$(Build.BuildNumber)
  displayName: 'Hacky Docker build'

- task: Docker@2
  displayName: push yngdieng-web-staging (DockerHub)
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-staging
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push yngdieng-web-staging (Aliyun)
  inputs:
    command: push
    repository: zingzeu/yngdieng-web-staging
    containerRegistry: aliyunContainerRegistry
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: push yngdieng-web-prod (DockerHub)
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-prod
    containerRegistry: dockerHub
    tags: |
      ci-$(Build.BuildNumber)

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: push yngdieng-web-prod (Aliyun)
  inputs:
    command: push
    repository: zingzeu/yngdieng-web-prod
    containerRegistry: aliyunContainerRegistry
    tags: |
      ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push yngdieng-backend (DockerHub)
  inputs:
    command: push
    repository: ztl8702/yngdieng-backend
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push yngdieng-backend (Aliyun)
  inputs:
    command: push
    repository: zingzeu/yngdieng-backend
    containerRegistry: aliyunContainerRegistry
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push opencc-daemon (DockerHub)
  inputs:
    command: push
    repository: ztl8702/opencc-daemon
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)
       
- task: Docker@2
  displayName: push opencc-daemon (Aliyun)
  inputs:
    command: push
    repository: zingzeu/opencc-daemon
    containerRegistry: aliyunContainerRegistry
    tags: |
       ci-$(Build.BuildNumber)
