# Build docker images

trigger:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_DISK_CACHE: $(Pipeline.Workspace)/.bazelcache
  BAZEL_OUTPUT_BASE: $(Pipeline.Workspace)/.bazel
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: 'ubuntu-latest'

steps:
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
- task: Cache@2
  displayName: "Cache: Bazel diskcache"
  inputs:
    key: 'bazel | "$(Agent.OS)" | disk'
    path: $(BAZEL_DISK_CACHE)

- task: Cache@2
  displayName: "Cache: Bazel external deps"
  inputs:
    key: 'bazel | "$(Agent.OS)" | external'
    path: $(BAZEL_OUTPUT_BASE)/external

- task: Cache@2
  displayName: "Cache: yarn"
  inputs:
    key: 'yarn | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
      yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  
- script: |
    echo "build --disk_cache=$(BAZEL_DISK_CACHE)" >> .bazelrc
    echo "build --output_base=$(BAZEL_OUTPUT_BASE)" >> .bazelrc

- script: |
    sudo apt install curl
    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    sudo apt update && sudo apt install bazel
  displayName: 'Install bazel'

- script: |
    bazel build //web/src/...
  displayName: 'Bazel build //web/src/...'

- script: |
    ./docker_build.sh ci-$(Build.BuildNumber)
  displayName: 'Hacky Docker build'

# DEBUG. TODO: remove
- script: |
    yarn cache dir
    echo ""
    echo "======"
    echo ""
    yarn cache list
  displayName: "debug: Yarn cache"

- task: Docker@2
  displayName: push ztl8702/yngdieng-web-staging
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-staging
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: push ztl8702/yngdieng-web-prod
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-prod
    containerRegistry: dockerHub
    tags: |
      ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push ztl8702/yngdieng-backend
  inputs:
    command: push
    repository: ztl8702/yngdieng-backend
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)
