# Build docker images

trigger:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_CACHE: $(Pipeline.Workspace)/.bazelcache

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  inputs:
    key: bazel
    path: $(BAZEL_CACHE)
    cacheHitVar: CACHE_RESTORED
- script: |
    echo "build --disk_cache=$(BAZEL_CACHE)" >> .bazelrc
- script: |
    sudo apt install curl
    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    sudo apt update && sudo apt install bazel
  displayName: 'Install bazel'

- script: |
    bazel build //web/src/...
  displayName: 'Bazel build //web/src/...'

- script: |
    ./docker_build.sh ci-$(Build.BuildNumber)
  displayName: 'Hacky Docker build'

- task: Docker@2
  displayName: push ztl8702/yngdieng-web-staging
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-staging
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)

- task: Docker@2
  displayName: push ztl8702/yngdieng-web-prod
  inputs:
    command: push
    repository: ztl8702/yngdieng-web-prod
    containerRegistry: dockerHub
    tags: |
      ci-$(Build.BuildNumber)
    #TODO: only run on commit

- task: Docker@2
  displayName: push ztl8702/yngdieng-backend
  inputs:
    command: push
    repository: ztl8702/yngdieng-backend
    containerRegistry: dockerHub
    tags: |
       ci-$(Build.BuildNumber)
