# Build and test .NET code

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - server/*
    - servertests/*

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_CACHE: $(Pipeline.Workspace)/.bazelcache

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    pushd server && \
    dotnet build && \
    popd && \
    pushd servertests/backend && \
    dotnet test && \
    popd
  displayName: 'dotnet build & test'
