# Build miniapp

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - js/packages/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - js/packages/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd js/packages/miniapp
    yarn install
    echo $(CI_PRIVATE_KEY) | base64 -d > /tmp/miniapp_key
  displayName: 'setup'
  env:
    CI_PRIVATE_KEY: $(CI_PRIVATE_KEY)

- script: |
    cd js/packages/miniapp
    export NODE_ENV=production
    yarn build:weapp
  displayName: 'build'

- script: |
    cd js/packages/miniapp
    yarn ci:upload $(Build.BuildNumber)
  displayName: 'upload'