# Build miniapp

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - miniapp/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd miniapp
    yarn install
  displayName: 'yarn install'

- script: |
    cd miniapp
    export NODE_ENV=production
    yarn build:weapp
  displayName: 'build'

  - script: |
    yarn ci:upload $(Build.BuildNumber)
  displayName: 'build'