# Build miniapp

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - miniapp/*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - miniapp/*

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd miniapp
    yarn global add @tarojs/cli
    yarn install
    echo $(CI_PRIVATE_KEY) >> /tmp/miniapp_key
  displayName: 'setup'
  env:
    CI_PRIVATE_KEY: $(CI_PRIVATE_KEY)

- script: |
    cd miniapp
    export NODE_ENV=production
    yarn build:weapp
  displayName: 'build'

- script: |
    cd miniapp
    yarn ci:upload $(Build.BuildNumber)
  displayName: 'upload'