# Test //web

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - assets/*
    - shared/*
    - web/*
    - package.json
    - WORKSPACE

pr:
  branches:
    include:
    - master
  paths:
    include:
    - assets/*
    - shared/*
    - web/*
    - package.json
    - WORKSPACE

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_CACHE: $(Pipeline.Workspace)/.bazelcache

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  name: gcpKey
  inputs:
    secureFile: 'yngdieng-azdo-gcp-secret.json'

- script: |
    echo "common --color=no
    common --curses=yes
    
    build --disk_cache=$(BAZEL_CACHE)
    build --remote_http_cache=https://storage.googleapis.com/yngdieng-bazel-cache
    build --google_credentials=$(gcpKey.secureFilePath)
    build --show_progress_rate_limit=0
    build --show_task_finish
    build --show_timestamps
    build --worker_verbose" >> .bazelrc
- script: |
    sudo apt install curl
    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    sudo apt update && sudo apt install bazel
  displayName: 'Install bazel'

- script: |
    bazel test --config=release //web/src/... //web/e2e/...
  displayName: 'Bazel Test'
