# Test //web

trigger:
- master

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true

variables:
  BAZEL_CACHE: $(Pipeline.Workspace)/.bazelcache

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    sudo apt install curl
    curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    sudo apt update && sudo apt install bazel
  displayName: 'Install bazel'

- script: |
    bazel test --config=release //web/...
  displayName: 'Bazel Test //web/...'
