version = 1

[merge]
method = "squash"
automerge_label = "automerge"
require_automerge_label = true
dont_wait_on_status_checks = ["buildkite/yngdieng-web-build"]

[merge.message]
# use title of PR for merge commit.
title = "pull_request_title"
# use body of PR for merge commit.
body = "pull_request_body"
# add the PR number to the merge commit title, like GitHub.
include_pr_number = true
# use the default markdown content of the PR for the merge commit.
body_type = "markdown"
# remove html comments to auto remove PR templates.
strip_html_comments = true
