pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=dotnet-tests
      - status-success=web-tests
      - status-success=docker-images
      - base=master
    actions:
      merge:
        method: squash
