const path = require('path');

module.exports = {
  stories: ['../stories/**/*.stories.mdx', '@yngdieng-web-app/**/*.stories.js'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async (config, options) => {
    config.watch = false;
    config.resolve.extensions = ['.js', '.json'];
    // Webpack doesn't recognize UMD modules (which are generated by
    // the Typescript compiler invoked by Bazel)
    //
    // This loader removes UMD wrapper.
    config.module.rules.push({
      test: /@yngdieng-web-app\/.*\.js$/,
      use: ['umd-compat-loader'],
    });
    console.log(config);
    return config;
  },
};
