load("@io_bazel_rules_dotnet//dotnet:defs.bzl", "nuget_package")

def yngdieng_nuget_packages():
    ### Generated by the tool
    nuget_package(
        name = "csvhelper",
        package = "csvhelper",
        version = "12.2.1",
        sha256 = "2b2fb6a25b4bb8052f06f40fea026bd46e70c0e6a151cd8d0c2379f66507dd63",
        core_lib = {
            "netcoreapp2.0": "lib/netstandard2.0/CsvHelper.dll",
            "netcoreapp2.1": "lib/netstandard2.0/CsvHelper.dll",
        },
        net_lib = {
            "net45": "lib/net45/CsvHelper.dll",
            "net451": "lib/net45/CsvHelper.dll",
            "net452": "lib/net45/CsvHelper.dll",
            "net46": "lib/net45/CsvHelper.dll",
            "net461": "lib/net45/CsvHelper.dll",
            "net462": "lib/net45/CsvHelper.dll",
            "net47": "lib/net47/CsvHelper.dll",
            "net471": "lib/net47/CsvHelper.dll",
            "net472": "lib/net47/CsvHelper.dll",
            "netstandard2.0": "lib/netstandard2.0/CsvHelper.dll",
        },
        mono_lib = "lib/net47/CsvHelper.dll",
        net_deps = {
            "net45": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net45_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net45_system.valuetuple.dll",
            ],
            "net451": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net451_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net451_system.valuetuple.dll",
            ],
            "net452": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net452_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net452_system.valuetuple.dll",
            ],
            "net46": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net46_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net46_system.valuetuple.dll",
            ],
            "net461": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net461_system.valuetuple.dll",
            ],
            "net462": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_microsoft.csharp.dll",
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net462_system.valuetuple.dll",
            ],
            "net47": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net47_microsoft.csharp.dll",
            ],
            "net471": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net471_microsoft.csharp.dll",
            ],
            "net472": [
            "@io_bazel_rules_dotnet//dotnet/stdlib.net:net472_microsoft.csharp.dll",
            ],
        },
        mono_deps = [
            "@io_bazel_rules_dotnet//dotnet/stdlib:microsoft.csharp.dll",
        ],
        core_files = {
            "netcoreapp2.0": [
            "lib/netstandard2.0/CsvHelper.dll",
            ],
            "netcoreapp2.1": [
            "lib/netstandard2.0/CsvHelper.dll",
            ],
        },
        net_files = {
            "net45": [
            "lib/net45/CsvHelper.dll",
            ],
            "net451": [
            "lib/net45/CsvHelper.dll",
            ],
            "net452": [
            "lib/net45/CsvHelper.dll",
            ],
            "net46": [
            "lib/net45/CsvHelper.dll",
            ],
            "net461": [
            "lib/net45/CsvHelper.dll",
            ],
            "net462": [
            "lib/net45/CsvHelper.dll",
            ],
            "net47": [
            "lib/net47/CsvHelper.dll",
            ],
            "net471": [
            "lib/net47/CsvHelper.dll",
            ],
            "net472": [
            "lib/net47/CsvHelper.dll",
            ],
            "netstandard2.0": [
            "lib/netstandard2.0/CsvHelper.dll",
            ],
        },
        mono_files = [
            "lib/net47/CsvHelper.dll",
        ],
    )
    ### End of generated by the tool
